apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-browns
  labels:
    app: hash-browns
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hash-browns
      tier: web
  template:
    metadata:
      labels:
        app: hash-browns
        tier: web
    spec:
      containers:
      - name: hash-browns
        image: alexellis2/hash-browns
        ports:
        - containerPort: 8080