apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hash-browns
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http: 
      paths:
      - path: /
        backend:
          serviceName: hash-browns
          servicePort: 8080
