apiVersion: v1
kind: Service
metadata:
  labels:
    app: hash-browns
  name: hash-browns
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hash-browns
  sessionAffinity: None
  type: NodePort