apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hello-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http: 
      paths:
      - path: /helloworld
        backend:
          serviceName: hello-app
          servicePort: 8080
